using System;
using System.Collections;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Net;
using System.Net.Sockets;
using System.Text;
using UnityEngine;

/// <summary>
/// Sends Quest hand poses, left-hand pinch drawing strokes, and optional Quest microphone audio to the HoloLens.
/// Receiver contract:
/// - poseSpace "CameraLocal" means points were stored relative to the Quest reference camera. The HoloLens receiver
///   should convert each stroke point through its own reference camera into HoloLens world space once, then leave it there.
/// - poseSpace "World" means stroke points can be used directly as world positions.
/// - strokeEvents contain "begin", "point", and "end" actions. "begin" creates a persistent red LineRenderer, "point"
///   appends 3D points, and "end" finalizes the line without destroying it on the HoloLens.
/// - when projectStrokeOntoDepth is enabled, stroke points are already projected from the Quest reference camera through
///   the pinch midpoint onto the measured depth image. The receiver should place the red line at those 3D points directly,
///   without attaching it to the billboard.
/// - audioFrame contains continuous microphone audio as PCM16 little-endian Base64 data. Decode it, enqueue it by sequence,
///   and feed it into a streaming AudioSource. Audio is independent from the pinch gesture.
/// Quest-local stroke previews are temporary only on the Quest and can be destroyed after questStrokeLifetimeSeconds.
/// </summary>
[DefaultExecutionOrder(100)]
[DisallowMultipleComponent]
[AddComponentMenu("MedXR/Quest Hand Data Sender")]
public sealed class QuestHandDataSender : MonoBehaviour
{
    [Header("Network")]
    public bool sendOnEnable = true;
    public bool useRunOnceHost = true;
    public string targetHost = "";
    public bool useLocalhostInEditor = true;
    public string editorTargetHost = "127.0.0.1";
    public int targetPort = 5055;
    public float sendRateHz = 30f;
    [Tooltip("Delay starting UDP networking so Quest rendering and Meta systems can finish startup first.")]
    public float networkStartDelaySeconds = 1f;
    [Tooltip("Minimum seconds between target host resolve attempts when the endpoint is not ready.")]
    public float targetResolveRetrySeconds = 1f;
    [Tooltip("Allow DNS host names. Keep this off for Quest builds and prefer direct IPv4 addresses to avoid startup stalls.")]
    public bool allowDnsHostResolution = false;

    [Header("Pose space")]
    public bool sendCameraRelativePoses = true;
    public bool autoFindReferenceCamera = true;
    public string referenceCameraName = "CenterEyeAnchor";
    public Transform referenceCamera;
    public float positionScale = 1f;

    [Header("Meta hand sources")]
    public bool autoFindHands = true;
    public string leftHandAnchorName = "LeftHandAnchor";
    public string rightHandAnchorName = "RightHandAnchor";
    public OVRHand leftHand;
    public OVRHand rightHand;
    public OVRSkeleton leftSkeleton;
    public OVRSkeleton rightSkeleton;

    [Header("WebRTC audio")]
    [Tooltip("Use bidirectional WebRTC audio instead of embedding PCM audio in hand-data UDP packets.")]
    public bool useWebRtcAudio = true;
    public int webRtcLocalSignalingPort = 5077;
    public int webRtcRemoteSignalingPort = 5076;
    public float webRtcStartupDelaySeconds = 0.75f;
    public bool logWebRtcAudioStatus = true;

    [Header("Billboard-aligned right hand")]
    [Tooltip("Translate only the streamed right hand so its index fingertip reaches the visible red billboard marker. Left-hand and stroke data remain unchanged.")]
    public bool alignStreamedRightHandToBillboardMarker = true;
    [Tooltip("Marker generated by FingerPosition. If empty, the sender finds the marker source used by DepthDistance.")]
    public FingerPosition billboardMarkerSource;
    public bool autoFindBillboardMarkerSource = true;
    public OVRSkeleton.BoneId billboardAnchorTipId = OVRSkeleton.BoneId.Hand_IndexTip;

    [Header("Tracking")]
    public bool requireHighConfidence = false;
    public bool sendUntrackedFrames = true;

    [Header("Left pinch stroke")]
    public bool enableLeftPinchStroke = true;
    [Tooltip("Use OVRHand.GetFingerIsPinching from the Meta Hand Tracking Building Block instead of a custom distance threshold.")]
    public bool useMetaHandTrackingBlockPinch = true;
    [Tooltip("Optional world-space point used for drawing instead of the Meta hand pinch point.")]
    public Transform strokePointOverride;
    [Tooltip("Project the stroke point through the depth billboard and draw at the measured depth instead of at the hand.")]
    public bool projectStrokeOntoDepth = true;
    [Tooltip("Apply the same billboard center/edge calibration used by the streamed right hand to projected pinch strokes.")]
    public bool applyBillboardCalibrationToStroke = true;
    [Tooltip("DepthDistance component used to convert the pinch midpoint into a measured depth point.")]
    public DepthDistance depthProjectionSource;
    [Tooltip("Automatically find a DepthDistance component if none is assigned.")]
    public bool autoFindDepthProjectionSource = true;
    [Tooltip("Camera used for depth projection. Falls back to referenceCamera when empty.")]
    public Transform depthProjectionCamera;
    [Tooltip("If true, invalid or zero depth samples do not create stroke points instead of falling back to the hand point.")]
    public bool skipStrokePointsWithoutDepth = true;
    [Tooltip("Reject projected stroke points that are too close to the reference camera. This prevents depth dropouts from drawing lines back to the headset.")]
    public bool rejectStrokePointsNearCamera = true;
    [Tooltip("Smallest allowed forward distance from the reference camera to a projected stroke point.")]
    public float minimumStrokeDistanceFromCamera = 0.35f;
    [Tooltip("Reject a projected stroke point when it jumps this much closer to the camera than the last accepted projected point. Set <= 0 to disable.")]
    public float maximumStrokeHeadwardJump = 0.2f;
    [Tooltip("Reject a projected stroke point when it is this far away from the last accepted projected point. Set <= 0 to disable.")]
    public float maximumStrokePointJump = 0.65f;
    public float strokePointSpacing = 0.01f;
    public float questStrokeLifetimeSeconds = 10f;
    public float strokeLineWidth = 0.01f;
    public float previewMinimumVisibleLength = 0.015f;
    public Color strokeColor = Color.red;
    public bool showQuestStrokePreview = true;
    [Tooltip("Render the Quest-local stroke preview as a screen-ray overlay so the depth/RGB billboard cannot hide it. Sent stroke points stay unchanged.")]
    public bool keepQuestStrokePreviewVisible = true;
    [Tooltip("How far the Quest-local preview is pulled toward the camera while staying on the same view ray.")]
    public float questStrokePreviewCameraOffset = 0.04f;

    [Header("Quest pinch depth hand preview")]
    [Tooltip("While the left hand pinches, show a local visual copy at the measured depth. Sent left-hand poses remain unchanged.")]
    public bool showLeftHandAtDepthWhilePinching = true;
    public float pinchDepthHandSmoothingTime = 0.04f;
    public float pinchDepthHandMaximumSpeed = 1.5f;

    [Header("Quest microphone audio")]
    public bool sendQuestMicrophoneAudio = true;
    public string microphoneDeviceName = "";
    [Tooltip("Network output sample rate. If the Quest captures at another rate, audio is resampled before sending.")]
    public int audioSampleRate = 16000;
    public int audioPacketRateHz = 60;
    public float audioGain = 1f;
    [Tooltip("Send microphone audio as a small audio-only UDP packet instead of bundling it into the larger hand pose packet.")]
    public bool sendAudioAsSeparatePacket = true;
    [Tooltip("Resample outgoing audio to audioSampleRate. Keep this on for stable low-bandwidth Quest-to-HoloLens audio.")]
    public bool resampleAudioToConfiguredSampleRate = true;
    [Tooltip("Downmix outgoing audio to mono. This keeps UDP packets small enough to avoid Wi-Fi fragmentation.")]
    public bool downmixAudioToMono = true;
    [Tooltip("Largest microphone slice to put into one UDP audio packet if Unity frames arrive late. Keep this small for UDP.")]
    public float maximumAudioPacketDurationSeconds = 0.025f;
    [Tooltip("Maximum number of small audio packets that may be sent in one Unity frame to catch up after a slow frame.")]
    public int maximumAudioPacketsPerUpdate = 3;
    public bool logAudioStatus = false;
    public bool saveAudioDiagnosticsToFile = false;
    public string audioDiagnosticsFolderName = "AudioDiagnostics";
    [Tooltip("Delay microphone startup after the sender is enabled. This avoids startup-time permission/audio races on Quest.")]
    public float microphoneStartDelaySeconds = 1f;
    [Tooltip("Save the exact outgoing PCM16 audio stream to a WAV file for debugging on device and in the editor.")]
    public bool saveOutgoingAudioWav = false;
    public string audioWavFolderName = "AudioWavCaptures";
    public string outgoingAudioWavSubfolderName = "Sender";
    public string outgoingAudioWavFileName = "quest_sender_outgoing.wav";
    public bool timestampAudioWavFiles = true;
    [Range(0.1f, 1f)]
    [Tooltip("Ceiling used by the soft limiter after audioGain. Lower values reduce distortion and clipping.")]
    public float audioLimiterCeiling = 0.9f;

    [Header("Debug")]
    public bool logConnectionChanges = true;
    public bool logPackets = false;
    public bool warnAboutLinkLocalTarget = true;

    private readonly HandFramePacket packet = new HandFramePacket();
    private readonly List<HandFrame> frameBuffer = new List<HandFrame>(2);
    private readonly List<JointPose> jointBuffer = new List<JointPose>(32);
    private readonly List<StrokeEvent> strokeEventQueue = new List<StrokeEvent>(16);
    private readonly List<Vector3> currentQuestStrokePoints = new List<Vector3>(64);
    private readonly HandFramePacket audioOnlyPacket = new HandFramePacket();
    private UdpClient udpClient;
    private IPEndPoint targetEndPoint;
    private string resolvedHost;
    private int resolvedPort;
    private float nextSendTime;
    private float nextFindTime;
    private float nextReferenceFindTime;
    private float nextDepthProjectionFindTime;
    private float nextBillboardMarkerFindTime;
    private float nextTargetResolveTime;
    private bool isSending;
    private Coroutine startSenderCoroutine;
    private bool warnedAboutMissingHost;
    private bool warnedAboutMissingHands;
    private bool warnedAboutLinkLocalTarget;
    private bool warnedAboutMissingLeftPinchSource;
    private bool warnedAboutMissingStrokePoint;
    private bool warnedAboutMissingDepthProjectionSource;
    private bool currentStrokePointSkippedForDepth;
    private bool leftPinchWasActive;
    private bool hasLastDepthProjectedStrokePoint;
    private Vector3 lastDepthProjectedStrokePoint;
    private bool hasLastDepthProjectedForwardDistance;
    private float lastDepthProjectedForwardDistance;
    private bool hasSmoothedRightHandOffset;
    private Vector3 smoothedRightHandOffset;
    private Vector3 rightHandOffsetVelocity;
    private bool hasCurrentPinchDepthPoint;
    private Vector3 currentPinchDepthPoint;
    private GameObject leftDepthPreviewRoot;
    private GameObject leftDepthPreviewClone;
    private readonly List<TransformPair> leftDepthPreviewTransformPairs = new List<TransformPair>(64);
    private readonly List<RendererState> originalLeftRendererStates = new List<RendererState>(8);
    private readonly List<Renderer> leftDepthPreviewRenderers = new List<Renderer>(8);
    private bool leftDepthPreviewVisible;
    private bool hasSmoothedLeftDepthPreviewOffset;
    private Vector3 smoothedLeftDepthPreviewOffset;
    private Vector3 leftDepthPreviewOffsetVelocity;
    private string activeStrokeId;
    private int nextStrokeId = 1;
    private LineRenderer activeQuestStrokeLine;
    private Material questStrokeMaterial;
    private AudioClip microphoneClip;
    private string activeMicrophoneDeviceName;
    private int microphoneReadPosition;
    private int audioSequence;
    private float nextAudioPacketTime;
    private float[] audioFloatBuffer;
    private float[] audioOutputFloatBuffer;
    private byte[] audioByteBuffer;
    private bool microphoneStartRequested;
    private bool microphonePermissionDenied;
    private bool microphoneStartFailed;
    private float earliestMicrophoneStartTime;
    private float nextAudioStatusLogTime;
    private int sentAudioFrameCount;
    private StreamWriter audioDiagnosticsWriter;
    private float nextAudioDiagnosticsFlushTime;
    private Pcm16WavWriter outgoingAudioWavWriter;
    private int outgoingAudioWavSampleRate;
    private int outgoingAudioWavChannels;
    private WebRtcAudioPeer webRtcAudioPeer;

    private void OnEnable()
    {
        StartWebRtcAudio();

        if (sendOnEnable)
        {
            StartSenderDelayed();
        }
    }

    private void Start()
    {
        if (autoFindHands)
        {
            FindHandSources();
        }

        if (autoFindReferenceCamera)
        {
            FindReferenceCamera();
        }

        if (autoFindDepthProjectionSource)
        {
            FindDepthProjectionSource();
        }

        if (autoFindBillboardMarkerSource)
        {
            FindBillboardMarkerSource();
        }

    }

    private void OnDisable()
    {
        StopWebRtcAudio();
        HideLeftDepthHandPreview();
        StopSender();
        StopMicrophoneCapture();
        CloseAudioDiagnosticsWriter();
        CloseOutgoingAudioWavWriter();
    }

    private void OnDestroy()
    {
        StopWebRtcAudio();
        DestroyLeftDepthHandPreview();
        StopSender();
        StopMicrophoneCapture();
        CloseAudioDiagnosticsWriter();
        CloseOutgoingAudioWavWriter();

        if (questStrokeMaterial != null)
        {
            Destroy(questStrokeMaterial);
            questStrokeMaterial = null;
        }
    }

    private void Update()
    {
        if (!isSending)
        {
            return;
        }

        if (autoFindHands && Time.unscaledTime >= nextFindTime)
        {
            nextFindTime = Time.unscaledTime + 1f;
            if (!HasBothSkeletons())
            {
                FindHandSources();
            }
        }

        if (autoFindReferenceCamera && referenceCamera == null && Time.unscaledTime >= nextReferenceFindTime)
        {
            nextReferenceFindTime = Time.unscaledTime + 1f;
            FindReferenceCamera();
        }

        if (autoFindDepthProjectionSource && depthProjectionSource == null && Time.unscaledTime >= nextDepthProjectionFindTime)
        {
            nextDepthProjectionFindTime = Time.unscaledTime + 1f;
            FindDepthProjectionSource();
        }

        if (autoFindBillboardMarkerSource && billboardMarkerSource == null && Time.unscaledTime >= nextBillboardMarkerFindTime)
        {
            nextBillboardMarkerFindTime = Time.unscaledTime + 1f;
            FindBillboardMarkerSource();
        }

        UpdateLeftPinchStroke();

        if (sendAudioAsSeparatePacket && !useWebRtcAudio)
        {
            SendDueAudioFrames();
        }

        float interval = sendRateHz > 0f ? 1f / sendRateHz : 0f;
        if (interval > 0f && Time.unscaledTime < nextSendTime)
        {
            return;
        }

        nextSendTime = Time.unscaledTime + interval;
        SendCurrentFrame();
    }

    private void LateUpdate()
    {
        UpdateLeftDepthHandPreview();
    }

    public void StartSender()
    {
        startSenderCoroutine = null;
        if (isSending)
        {
            return;
        }

        try
        {
            udpClient = new UdpClient();
            isSending = true;
            warnedAboutMissingHost = false;
            warnedAboutMissingHands = false;
            warnedAboutLinkLocalTarget = false;
            warnedAboutMissingLeftPinchSource = false;
            warnedAboutMissingStrokePoint = false;
            microphonePermissionDenied = false;
            microphoneStartFailed = false;
            earliestMicrophoneStartTime = Time.unscaledTime + Mathf.Max(0f, microphoneStartDelaySeconds);
            nextTargetResolveTime = 0f;
        }
        catch (Exception e)
        {
            isSending = false;
            Debug.LogError("QuestHandDataSender could not start UDP sender: " + e.Message);
        }
    }

    private void StartSenderDelayed()
    {
        if (startSenderCoroutine != null)
        {
            StopCoroutine(startSenderCoroutine);
        }

        startSenderCoroutine = StartCoroutine(StartSenderAfterDelay());
    }

    private IEnumerator StartSenderAfterDelay()
    {
        float delay = Mathf.Max(0f, networkStartDelaySeconds);
        if (delay > 0f)
        {
            yield return new WaitForSeconds(delay);
        }

        StartSender();
    }

    public void StopSender()
    {
        if (startSenderCoroutine != null)
        {
            StopCoroutine(startSenderCoroutine);
            startSenderCoroutine = null;
        }

        FinishActiveStrokePreview();
        leftPinchWasActive = false;
        activeStrokeId = null;
        ResetRightHandBillboardAlignment();
        currentQuestStrokePoints.Clear();
        strokeEventQueue.Clear();

        isSending = false;
        targetEndPoint = null;
        resolvedHost = null;
        resolvedPort = 0;

        if (udpClient != null)
        {
            udpClient.Close();
            udpClient = null;
        }
    }

    private void SendCurrentFrame()
    {
        if (udpClient == null || !ResolveTargetEndPoint())
        {
            return;
        }

        AudioFrame audioFrame = sendAudioAsSeparatePacket || useWebRtcAudio
            ? null
            : TryBuildAudioFrame();
        BuildPacket(audioFrame);
        bool hasHands = packet.hands != null && packet.hands.Length > 0;
        bool hasStrokes = packet.strokeEvents != null && packet.strokeEvents.Length > 0;
        bool hasAudio = packet.audioFrame != null && !string.IsNullOrEmpty(packet.audioFrame.samplesBase64);
        if (!hasHands && !hasStrokes && !hasAudio)
        {
            if (audioFrame == null && !warnedAboutMissingHands)
            {
                warnedAboutMissingHands = true;
                Debug.LogWarning("QuestHandDataSender found no Meta hand sources, stroke events, or audio samples to send.");
            }
        }
        else if (SendPacket(packet))
        {
            strokeEventQueue.Clear();
        }
    }

    private void SendDueAudioFrames()
    {
        if (!sendQuestMicrophoneAudio || udpClient == null || !ResolveTargetEndPoint())
        {
            return;
        }

        int maxPackets = Mathf.Clamp(maximumAudioPacketsPerUpdate, 1, 8);
        for (int i = 0; i < maxPackets; i++)
        {
            AudioFrame audioFrame = TryBuildAudioFrame();
            if (audioFrame == null)
            {
                return;
            }

            SendAudioPacket(audioFrame);
        }
    }

    private bool SendPacket(HandFramePacket packetToSend)
    {
        try
        {
            string json = JsonUtility.ToJson(packetToSend);
            byte[] bytes = Encoding.UTF8.GetBytes(json);
            udpClient.Send(bytes, bytes.Length, targetEndPoint);

            if (logPackets)
            {
                Debug.Log("QuestHandDataSender sent " + bytes.Length + " bytes to " + targetEndPoint + " (" + packetToSend.packetType + ")");
            }

            return true;
        }
        catch (Exception e)
        {
            Debug.LogWarning("QuestHandDataSender UDP send failed: " + e.Message);
            targetEndPoint = null;
            return false;
        }
    }

    private void SendAudioPacket(AudioFrame audioFrame)
    {
        audioOnlyPacket.packetType = "questAudio";
        audioOnlyPacket.poseSpace = "";
        audioOnlyPacket.hands = null;
        audioOnlyPacket.strokeEvents = null;
        audioOnlyPacket.audioFrame = audioFrame;
        SendPacket(audioOnlyPacket);
        audioOnlyPacket.audioFrame = null;
    }

    private void BuildPacket(AudioFrame audioFrame)
    {
        frameBuffer.Clear();
        packet.packetType = "questFrame";
        packet.poseSpace = sendCameraRelativePoses && referenceCamera != null ? "CameraLocal" : "World";

        AddHandFrame("Left", leftHand, leftSkeleton);
        AddHandFrame("Right", rightHand, rightSkeleton);

        packet.hands = frameBuffer.ToArray();
        packet.strokeEvents = strokeEventQueue.Count > 0 ? strokeEventQueue.ToArray() : null;
        packet.audioFrame = audioFrame;
    }

    private void AddHandFrame(string handedness, OVRHand hand, OVRSkeleton skeleton)
    {
        bool isTracked = IsHandTracked(hand, skeleton);
        bool isRightHand = string.Equals(handedness, "Right", StringComparison.OrdinalIgnoreCase);
        if (!isTracked && isRightHand)
        {
            ResetRightHandBillboardAlignment();
        }

        if (!isTracked && !sendUntrackedFrames)
        {
            return;
        }

        HandFrame frame = new HandFrame();
        frame.handedness = handedness;
        frame.isTracked = isTracked;
        frame.wrist = PoseData.Invalid;
        frame.joints = new JointPose[0];

        if (isTracked && skeleton != null && skeleton.Bones != null)
        {
            jointBuffer.Clear();
            Vector3 streamedWorldOffset = isRightHand
                ? GetRightHandBillboardOffset(skeleton)
                : Vector3.zero;

            for (int i = 0; i < skeleton.Bones.Count; i++)
            {
                OVRBone bone = skeleton.Bones[i];
                if (bone == null || bone.Transform == null)
                {
                    continue;
                }

                string jointName = bone.Id.ToString();
                PoseData pose = PoseData.FromTransform(
                    bone.Transform,
                    sendCameraRelativePoses ? referenceCamera : null,
                    positionScale,
                    streamedWorldOffset);

                if (IsWristBone(bone.Id) && !frame.wrist.isValid)
                {
                    frame.wrist = pose;
                }

                JointPose joint = new JointPose();
                joint.name = jointName;
                joint.pose = pose;
                jointBuffer.Add(joint);
            }

            frame.joints = jointBuffer.ToArray();
        }

        frameBuffer.Add(frame);
    }

    private void UpdateLeftPinchStroke()
    {
        if (!enableLeftPinchStroke || !IsLeftPinchActive())
        {
            hasCurrentPinchDepthPoint = false;
            EndActiveLeftPinchStroke();
            return;
        }

        Vector3 pinchPoint;
        currentStrokePointSkippedForDepth = false;
        if (!TryGetCurrentStrokeWorldPoint(out pinchPoint))
        {
            hasCurrentPinchDepthPoint = false;
            if (!currentStrokePointSkippedForDepth)
            {
                WarnAboutMissingStrokePoint();
            }
            return;
        }

        hasCurrentPinchDepthPoint = true;
        currentPinchDepthPoint = pinchPoint;

        if (!leftPinchWasActive)
        {
            BeginLeftPinchStroke(pinchPoint);
        }
        else
        {
            AppendLeftPinchStrokePoint(pinchPoint);
        }

        leftPinchWasActive = true;
    }

    private bool IsLeftPinchActive()
    {
        if (!useMetaHandTrackingBlockPinch)
        {
            return false;
        }

        if (leftHand == null || leftSkeleton == null)
        {
            if (autoFindHands)
            {
                FindHandSources();
            }
        }

        if (leftHand == null)
        {
            WarnAboutMissingLeftPinchSource();
            return false;
        }

        if (!leftHand.IsTracked || !leftHand.IsDataValid)
        {
            return false;
        }

        if (requireHighConfidence && !leftHand.IsDataHighConfidence)
        {
            return false;
        }

        warnedAboutMissingLeftPinchSource = false;
        return leftHand.GetFingerIsPinching(OVRHand.HandFinger.Index);
    }

    private bool TryGetCurrentStrokeWorldPoint(out Vector3 worldPoint)
    {
        Vector3 sourcePoint;
        if (strokePointOverride != null)
        {
            sourcePoint = strokePointOverride.position;
            return TryResolveStrokePoint(sourcePoint, out worldPoint);
        }

        Vector3 thumbTip;
        Vector3 indexTip;
        if (TryGetFingerTipPositions(leftSkeleton, out thumbTip, out indexTip))
        {
            sourcePoint = (thumbTip + indexTip) * 0.5f;
            return TryResolveStrokePoint(sourcePoint, out worldPoint);
        }

        if (leftHand != null && leftHand.IsPointerPoseValid)
        {
            Transform pointerPose = leftHand.PointerPose;
            if (pointerPose != null)
            {
                sourcePoint = pointerPose.position;
                return TryResolveStrokePoint(sourcePoint, out worldPoint);
            }
        }

        worldPoint = Vector3.zero;
        return false;
    }

    private bool TryResolveStrokePoint(Vector3 sourcePoint, out Vector3 worldPoint)
    {
        if (projectStrokeOntoDepth)
        {
            if (TryProjectStrokePointOntoDepth(sourcePoint, out worldPoint))
            {
                hasLastDepthProjectedStrokePoint = true;
                lastDepthProjectedStrokePoint = worldPoint;
                return true;
            }

            if (skipStrokePointsWithoutDepth)
            {
                currentStrokePointSkippedForDepth = true;
                worldPoint = Vector3.zero;
                return false;
            }

            if (leftPinchWasActive && hasLastDepthProjectedStrokePoint)
            {
                worldPoint = lastDepthProjectedStrokePoint;
                return IsFinite(worldPoint);
            }
        }

        worldPoint = sourcePoint;
        return IsFinite(worldPoint);
    }

    private bool TryProjectStrokePointOntoDepth(Vector3 sourcePoint, out Vector3 depthPoint)
    {
        depthPoint = Vector3.zero;

        if (depthProjectionSource == null && autoFindDepthProjectionSource)
        {
            if (Time.unscaledTime >= nextDepthProjectionFindTime)
            {
                nextDepthProjectionFindTime = Time.unscaledTime + 1f;
                FindDepthProjectionSource();
            }
        }

        if (depthProjectionSource == null)
        {
            WarnAboutMissingDepthProjectionSource();
            return false;
        }

        Transform projectionCamera = depthProjectionCamera != null ? depthProjectionCamera : referenceCamera;
        if (projectionCamera == null && autoFindReferenceCamera)
        {
            FindReferenceCamera();
            projectionCamera = referenceCamera;
        }

        if (projectionCamera == null)
        {
            WarnAboutMissingDepthProjectionSource();
            return false;
        }

        float depthMeters;
        float rawValue;
        Vector2 billboardUV;
        if (!depthProjectionSource.TryProjectWorldPointToDepth(
                sourcePoint,
                projectionCamera,
                out depthPoint,
                out depthMeters,
                out rawValue,
                out billboardUV))
        {
            return false;
        }

        if (applyBillboardCalibrationToStroke)
        {
            Vector2 centeredBillboardCoordinates = new Vector2(
                Mathf.Clamp(billboardUV.x * 2f - 1f, -1f, 1f),
                Mathf.Clamp(billboardUV.y * 2f - 1f, -1f, 1f));
            depthPoint += GetDepthScaledBillboardCorrection(
                projectionCamera,
                centeredBillboardCoordinates,
                depthMeters);
        }

        if (!IsFinite(depthPoint))
        {
            return false;
        }

        if (!IsProjectedStrokePointSafe(depthPoint, projectionCamera, out float forwardDistance))
        {
            return false;
        }

        hasLastDepthProjectedForwardDistance = true;
        lastDepthProjectedForwardDistance = forwardDistance;
        warnedAboutMissingDepthProjectionSource = false;
        return true;
    }

    private bool IsProjectedStrokePointSafe(Vector3 depthPoint, Transform projectionCamera, out float forwardDistance)
    {
        forwardDistance = 0f;

        if (projectionCamera == null || !IsFinite(depthPoint))
        {
            return false;
        }

        Vector3 cameraToPoint = depthPoint - projectionCamera.position;
        if (cameraToPoint.sqrMagnitude < 1e-8f)
        {
            return false;
        }

        Vector3 cameraForward = projectionCamera.forward;
        if (cameraForward.sqrMagnitude < 1e-8f)
        {
            return false;
        }

        forwardDistance = Vector3.Dot(cameraToPoint, cameraForward.normalized);
        if (!IsFinite(forwardDistance))
        {
            return false;
        }

        if (rejectStrokePointsNearCamera && forwardDistance < minimumStrokeDistanceFromCamera)
        {
            currentStrokePointSkippedForDepth = true;
            return false;
        }

        if (maximumStrokeHeadwardJump > 0f &&
            hasLastDepthProjectedForwardDistance &&
            forwardDistance < lastDepthProjectedForwardDistance - maximumStrokeHeadwardJump)
        {
            currentStrokePointSkippedForDepth = true;
            return false;
        }

        if (maximumStrokePointJump > 0f &&
            hasLastDepthProjectedStrokePoint &&
            Vector3.Distance(lastDepthProjectedStrokePoint, depthPoint) > maximumStrokePointJump)
        {
            currentStrokePointSkippedForDepth = true;
            return false;
        }

        return true;
    }

    private void WarnAboutMissingLeftPinchSource()
    {
        if (warnedAboutMissingLeftPinchSource)
        {
            return;
        }

        warnedAboutMissingLeftPinchSource = true;
        Debug.LogWarning("QuestHandDataSender could not find the left OVRHand from the Meta Hand Tracking Building Block.");
    }

    private void WarnAboutMissingStrokePoint()
    {
        if (warnedAboutMissingStrokePoint)
        {
            return;
        }

        warnedAboutMissingStrokePoint = true;
        Debug.LogWarning("QuestHandDataSender received a pinch select event but could not read a hand pinch point.");
    }

    private void WarnAboutMissingDepthProjectionSource()
    {
        if (warnedAboutMissingDepthProjectionSource)
        {
            return;
        }

        warnedAboutMissingDepthProjectionSource = true;
        Debug.LogWarning("QuestHandDataSender could not project the pinch stroke onto depth. Assign a DepthDistance component or keep autoFindDepthProjectionSource enabled.");
    }

    private void BeginLeftPinchStroke(Vector3 worldPoint)
    {
        activeStrokeId = "quest-left-pinch-" + nextStrokeId;
        nextStrokeId++;
        currentQuestStrokePoints.Clear();
        currentQuestStrokePoints.Add(worldPoint);
        QueueStrokeEvent("begin", worldPoint);

        if (showQuestStrokePreview)
        {
            CreateQuestStrokePreview(worldPoint);
        }
    }

    private void AppendLeftPinchStrokePoint(Vector3 worldPoint)
    {
        if (string.IsNullOrEmpty(activeStrokeId))
        {
            BeginLeftPinchStroke(worldPoint);
            return;
        }

        if (currentQuestStrokePoints.Count > 0)
        {
            Vector3 previousPoint = currentQuestStrokePoints[currentQuestStrokePoints.Count - 1];
            if (Vector3.Distance(previousPoint, worldPoint) < strokePointSpacing)
            {
                return;
            }
        }

        currentQuestStrokePoints.Add(worldPoint);
        QueueStrokeEvent("point", worldPoint);
        UpdateQuestStrokePreview();
    }

    private void EndActiveLeftPinchStroke()
    {
        if (!leftPinchWasActive && string.IsNullOrEmpty(activeStrokeId))
        {
            return;
        }

        if (!string.IsNullOrEmpty(activeStrokeId) && currentQuestStrokePoints.Count > 0)
        {
            Vector3 lastPoint = currentQuestStrokePoints[currentQuestStrokePoints.Count - 1];
            QueueStrokeEvent("end", lastPoint);
        }

        FinishActiveStrokePreview();
        leftPinchWasActive = false;
        hasCurrentPinchDepthPoint = false;
        hasLastDepthProjectedStrokePoint = false;
        lastDepthProjectedStrokePoint = Vector3.zero;
        hasLastDepthProjectedForwardDistance = false;
        lastDepthProjectedForwardDistance = 0f;
        activeStrokeId = null;
        currentQuestStrokePoints.Clear();
    }

    private void QueueStrokeEvent(string action, Vector3 worldPoint)
    {
        if (string.IsNullOrEmpty(activeStrokeId))
        {
            return;
        }

        StrokeEvent strokeEvent = new StrokeEvent();
        strokeEvent.id = activeStrokeId;
        strokeEvent.action = action;
        strokeEvent.point = PoseData.FromPosition(
            worldPoint,
            sendCameraRelativePoses ? referenceCamera : null,
            positionScale,
            Vector3.zero);
        strokeEvent.width = strokeLineWidth;
        strokeEvent.color = strokeColor;
        strokeEvent.timestamp = Time.unscaledTime;
        strokeEventQueue.Add(strokeEvent);
    }

    private Vector3 GetRightHandBillboardOffset(OVRSkeleton skeleton)
    {
        if (!alignStreamedRightHandToBillboardMarker ||
            skeleton == null ||
            !TryGetBoneWorldPosition(skeleton, billboardAnchorTipId, out Vector3 fingertipWorldPosition) ||
            !TryGetBillboardMarker(out Vector3 markerWorldPosition, out Vector2 centeredBillboardCoordinates))
        {
            return hasSmoothedRightHandOffset ? smoothedRightHandOffset : Vector3.zero;
        }

        Transform cameraTransform = referenceCamera != null ? referenceCamera : depthProjectionCamera;
        if (cameraTransform == null)
        {
            return Vector3.zero;
        }

        Vector3 cameraToMarker = markerWorldPosition - cameraTransform.position;
        float markerDepth = cameraToMarker.magnitude;
        if (markerDepth <= 0.001f || !IsFinite(markerDepth))
        {
            return hasSmoothedRightHandOffset ? smoothedRightHandOffset : Vector3.zero;
        }

        const float minimumDepth = 0.2f;
        const float maximumDepth = 1.5f;
        const float smoothingTime = 0.04f;
        const float maximumOffsetSpeed = 1.5f;

        float sharedDepth = Mathf.Clamp(markerDepth, minimumDepth, maximumDepth);

        Vector3 targetWorldPosition = cameraTransform.position + cameraToMarker.normalized * sharedDepth;
        targetWorldPosition += GetDepthScaledBillboardCorrection(
            cameraTransform,
            centeredBillboardCoordinates,
            sharedDepth);
        Vector3 targetOffset = targetWorldPosition - fingertipWorldPosition;
        if (!IsFinite(targetOffset))
        {
            return hasSmoothedRightHandOffset ? smoothedRightHandOffset : Vector3.zero;
        }

        if (!hasSmoothedRightHandOffset)
        {
            hasSmoothedRightHandOffset = true;
            smoothedRightHandOffset = Vector3.zero;
            rightHandOffsetVelocity = Vector3.zero;
        }

        smoothedRightHandOffset = Vector3.SmoothDamp(
            smoothedRightHandOffset,
            targetOffset,
            ref rightHandOffsetVelocity,
            smoothingTime,
            maximumOffsetSpeed,
            Mathf.Max(0.0001f, Time.unscaledDeltaTime));

        return smoothedRightHandOffset;
    }

    private bool TryGetBillboardMarker(
        out Vector3 markerWorldPosition,
        out Vector2 centeredBillboardCoordinates)
    {
        markerWorldPosition = Vector3.zero;
        centeredBillboardCoordinates = Vector2.zero;
        if (billboardMarkerSource == null && autoFindBillboardMarkerSource)
        {
            FindBillboardMarkerSource();
        }

        return billboardMarkerSource != null &&
               billboardMarkerSource.TryGetMarkerWorldPosition(out markerWorldPosition) &&
               billboardMarkerSource.TryGetCenteredBillboardCoordinates(out centeredBillboardCoordinates) &&
               IsFinite(markerWorldPosition);
    }

    private Vector3 GetDepthScaledBillboardCorrection(
        Transform cameraTransform,
        Vector2 centeredBillboardCoordinates,
        float depthMeters)
    {
        if (cameraTransform == null || depthMeters <= 0f)
        {
            return Vector3.zero;
        }

        Vector3 cameraLocalCorrection = new Vector3(
            0f,
            0f,
            0f);

        if (billboardMarkerSource != null && billboardMarkerSource.billboard != null)
        {
            BillboardFollow billboardFollow = billboardMarkerSource.billboard.GetComponent<BillboardFollow>();
            if (billboardFollow != null)
            {
                Vector2 correctionMeters = billboardFollow.GetHandCorrectionMeters(
                    centeredBillboardCoordinates,
                    depthMeters);
                cameraLocalCorrection.x = correctionMeters.x;
                cameraLocalCorrection.y = correctionMeters.y;
            }
        }

        return cameraTransform.TransformVector(cameraLocalCorrection);
    }

    private void ResetRightHandBillboardAlignment()
    {
        hasSmoothedRightHandOffset = false;
        smoothedRightHandOffset = Vector3.zero;
        rightHandOffsetVelocity = Vector3.zero;
    }

    private void StartWebRtcAudio()
    {
        if (!useWebRtcAudio)
        {
            return;
        }

        StopMicrophoneCapture();
        if (webRtcAudioPeer == null)
        {
            webRtcAudioPeer = GetComponent<WebRtcAudioPeer>();
            if (webRtcAudioPeer == null)
            {
                webRtcAudioPeer = gameObject.AddComponent<WebRtcAudioPeer>();
            }
        }

        webRtcAudioPeer.startupDelaySeconds = Mathf.Max(0f, webRtcStartupDelaySeconds);
        webRtcAudioPeer.logStatus = logWebRtcAudioStatus;
        webRtcAudioPeer.ConfigureAndStart(
            true,
            ResolveWebRtcTargetHost(),
            Mathf.Clamp(webRtcLocalSignalingPort, 1, 65535),
            Mathf.Clamp(webRtcRemoteSignalingPort, 1, 65535));
    }

    private void StopWebRtcAudio()
    {
        if (webRtcAudioPeer != null)
        {
            webRtcAudioPeer.StopPeer();
        }
    }

    private string ResolveWebRtcTargetHost()
    {
#if UNITY_EDITOR
        if (useLocalhostInEditor && !string.IsNullOrWhiteSpace(editorTargetHost))
        {
            return editorTargetHost.Trim();
        }
#endif
        if (useRunOnceHost && !string.IsNullOrWhiteSpace(run_once.host_address))
        {
            return run_once.host_address.Trim();
        }

        return string.IsNullOrWhiteSpace(targetHost) ? "" : targetHost.Trim();
    }

    private void UpdateLeftDepthHandPreview()
    {
        if (!showLeftHandAtDepthWhilePinching ||
            !hasCurrentPinchDepthPoint ||
            leftSkeleton == null ||
            !TryGetFingerTipPositions(leftSkeleton, out Vector3 thumbTip, out Vector3 indexTip))
        {
            HideLeftDepthHandPreview();
            return;
        }

        EnsureLeftDepthHandPreview();
        if (leftDepthPreviewRoot == null || leftDepthPreviewClone == null)
        {
            return;
        }

        Vector3 pinchMidpoint = (thumbTip + indexTip) * 0.5f;
        Vector3 targetOffset = currentPinchDepthPoint - pinchMidpoint;
        if (!IsFinite(targetOffset))
        {
            HideLeftDepthHandPreview();
            return;
        }

        if (!hasSmoothedLeftDepthPreviewOffset)
        {
            hasSmoothedLeftDepthPreviewOffset = true;
            smoothedLeftDepthPreviewOffset = Vector3.zero;
            leftDepthPreviewOffsetVelocity = Vector3.zero;
        }

        smoothedLeftDepthPreviewOffset = Vector3.SmoothDamp(
            smoothedLeftDepthPreviewOffset,
            targetOffset,
            ref leftDepthPreviewOffsetVelocity,
            Mathf.Max(0.001f, pinchDepthHandSmoothingTime),
            Mathf.Max(0.01f, pinchDepthHandMaximumSpeed),
            Mathf.Max(0.0001f, Time.unscaledDeltaTime));

        Transform sourceRoot = leftSkeleton.transform;
        leftDepthPreviewRoot.transform.SetPositionAndRotation(
            sourceRoot.position + smoothedLeftDepthPreviewOffset,
            sourceRoot.rotation);
        leftDepthPreviewRoot.transform.localScale = sourceRoot.lossyScale;
        leftDepthPreviewClone.transform.localPosition = Vector3.zero;
        leftDepthPreviewClone.transform.localRotation = Quaternion.identity;
        leftDepthPreviewClone.transform.localScale = Vector3.one;

        for (int i = 0; i < leftDepthPreviewTransformPairs.Count; i++)
        {
            TransformPair pair = leftDepthPreviewTransformPairs[i];
            if (pair.source == null || pair.preview == null)
            {
                continue;
            }

            pair.preview.localPosition = pair.source.localPosition;
            pair.preview.localRotation = pair.source.localRotation;
            pair.preview.localScale = pair.source.localScale;
        }

        SetLeftDepthHandPreviewVisible(true);
    }

    private void EnsureLeftDepthHandPreview()
    {
        if (leftDepthPreviewRoot != null || leftSkeleton == null)
        {
            return;
        }

        Transform sourceRoot = leftSkeleton.transform;
        leftDepthPreviewRoot = new GameObject("QuestLeftHandDepthPreviewRoot");
        leftDepthPreviewRoot.SetActive(false);
        leftDepthPreviewRoot.transform.SetPositionAndRotation(sourceRoot.position, sourceRoot.rotation);
        leftDepthPreviewRoot.transform.localScale = sourceRoot.lossyScale;

        leftDepthPreviewClone = Instantiate(sourceRoot.gameObject, leftDepthPreviewRoot.transform, false);
        leftDepthPreviewClone.name = "QuestLeftHandDepthPreviewVisual";
        leftDepthPreviewClone.transform.localPosition = Vector3.zero;
        leftDepthPreviewClone.transform.localRotation = Quaternion.identity;
        leftDepthPreviewClone.transform.localScale = Vector3.one;

        MonoBehaviour[] clonedBehaviours = leftDepthPreviewClone.GetComponentsInChildren<MonoBehaviour>(true);
        for (int i = 0; i < clonedBehaviours.Length; i++)
        {
            clonedBehaviours[i].enabled = false;
        }

        Collider[] clonedColliders = leftDepthPreviewClone.GetComponentsInChildren<Collider>(true);
        for (int i = 0; i < clonedColliders.Length; i++)
        {
            clonedColliders[i].enabled = false;
        }

        leftDepthPreviewTransformPairs.Clear();
        BuildLeftDepthPreviewTransformPairs(sourceRoot, leftDepthPreviewClone.transform);

        originalLeftRendererStates.Clear();
        Renderer[] sourceRenderers = sourceRoot.GetComponentsInChildren<Renderer>(true);
        for (int i = 0; i < sourceRenderers.Length; i++)
        {
            originalLeftRendererStates.Add(new RendererState
            {
                renderer = sourceRenderers[i],
                enabled = sourceRenderers[i].enabled
            });
        }

        leftDepthPreviewRenderers.Clear();
        leftDepthPreviewRenderers.AddRange(
            leftDepthPreviewClone.GetComponentsInChildren<Renderer>(true));
        for (int i = 0; i < leftDepthPreviewRenderers.Count; i++)
        {
            if (leftDepthPreviewRenderers[i] != null)
            {
                leftDepthPreviewRenderers[i].enabled = false;
            }
        }

        leftDepthPreviewVisible = false;
        leftDepthPreviewRoot.SetActive(true);
    }

    private void BuildLeftDepthPreviewTransformPairs(Transform source, Transform preview)
    {
        int childCount = Mathf.Min(source.childCount, preview.childCount);
        for (int i = 0; i < childCount; i++)
        {
            Transform sourceChild = source.GetChild(i);
            Transform previewChild = preview.GetChild(i);
            leftDepthPreviewTransformPairs.Add(new TransformPair
            {
                source = sourceChild,
                preview = previewChild
            });
            BuildLeftDepthPreviewTransformPairs(sourceChild, previewChild);
        }
    }

    private void SetLeftDepthHandPreviewVisible(bool visible)
    {
        if (leftDepthPreviewVisible == visible)
        {
            return;
        }

        leftDepthPreviewVisible = visible;
        for (int i = 0; i < originalLeftRendererStates.Count; i++)
        {
            RendererState state = originalLeftRendererStates[i];
            if (state.renderer == null)
            {
                continue;
            }

            if (visible)
            {
                state.enabled = state.renderer.enabled;
                state.renderer.enabled = false;
            }
            else
            {
                state.renderer.enabled = state.enabled;
            }
        }

        for (int i = 0; i < leftDepthPreviewRenderers.Count; i++)
        {
            Renderer renderer = leftDepthPreviewRenderers[i];
            if (renderer != null)
            {
                bool sourceWasVisible =
                    i >= originalLeftRendererStates.Count ||
                    originalLeftRendererStates[i].enabled;
                renderer.enabled = visible && sourceWasVisible;
            }
        }
    }

    private void HideLeftDepthHandPreview()
    {
        SetLeftDepthHandPreviewVisible(false);
        hasSmoothedLeftDepthPreviewOffset = false;
        smoothedLeftDepthPreviewOffset = Vector3.zero;
        leftDepthPreviewOffsetVelocity = Vector3.zero;
    }

    private void DestroyLeftDepthHandPreview()
    {
        HideLeftDepthHandPreview();
        if (leftDepthPreviewRoot != null)
        {
            Destroy(leftDepthPreviewRoot);
        }

        leftDepthPreviewRoot = null;
        leftDepthPreviewClone = null;
        leftDepthPreviewTransformPairs.Clear();
        originalLeftRendererStates.Clear();
        leftDepthPreviewRenderers.Clear();
    }

    private bool TryGetFingerTipPositions(OVRSkeleton skeleton, out Vector3 thumbTip, out Vector3 indexTip)
    {
        thumbTip = Vector3.zero;
        indexTip = Vector3.zero;

        if (skeleton == null || skeleton.Bones == null)
        {
            return false;
        }

        bool foundThumb = false;
        bool foundIndex = false;
        for (int i = 0; i < skeleton.Bones.Count; i++)
        {
            OVRBone bone = skeleton.Bones[i];
            if (bone == null || bone.Transform == null)
            {
                continue;
            }

            string boneName = bone.Id.ToString().ToLowerInvariant();
            if (!IsTipBoneName(boneName))
            {
                continue;
            }

            if (!foundThumb && boneName.Contains("thumb"))
            {
                thumbTip = bone.Transform.position;
                foundThumb = true;
            }
            else if (!foundIndex && (boneName.Contains("index") || boneName.Contains("pointer")))
            {
                indexTip = bone.Transform.position;
                foundIndex = true;
            }

            if (foundThumb && foundIndex)
            {
                return true;
            }
        }

        return false;
    }

    private static bool TryGetBoneWorldPosition(OVRSkeleton skeleton, OVRSkeleton.BoneId boneId, out Vector3 worldPosition)
    {
        worldPosition = Vector3.zero;
        if (skeleton == null || skeleton.Bones == null)
        {
            return false;
        }

        for (int i = 0; i < skeleton.Bones.Count; i++)
        {
            OVRBone bone = skeleton.Bones[i];
            if (bone != null && bone.Id == boneId && bone.Transform != null)
            {
                worldPosition = bone.Transform.position;
                return IsFinite(worldPosition);
            }
        }

        return false;
    }

    private static bool IsTipBoneName(string boneName)
    {
        return !string.IsNullOrEmpty(boneName) &&
               (boneName.Contains("tip") || boneName.Contains("end"));
    }

    private void CreateQuestStrokePreview(Vector3 firstPoint)
    {
        FinishActiveStrokePreview();

        GameObject strokeObject = new GameObject("Quest_LeftPinchStrokePreview");
        activeQuestStrokeLine = strokeObject.AddComponent<LineRenderer>();
        activeQuestStrokeLine.useWorldSpace = true;
        activeQuestStrokeLine.alignment = LineAlignment.View;
        activeQuestStrokeLine.textureMode = LineTextureMode.Stretch;
        activeQuestStrokeLine.numCapVertices = 4;
        activeQuestStrokeLine.numCornerVertices = 4;
        activeQuestStrokeLine.shadowCastingMode = UnityEngine.Rendering.ShadowCastingMode.Off;
        activeQuestStrokeLine.receiveShadows = false;
        activeQuestStrokeLine.startWidth = strokeLineWidth;
        activeQuestStrokeLine.endWidth = strokeLineWidth;
        activeQuestStrokeLine.startColor = strokeColor;
        activeQuestStrokeLine.endColor = strokeColor;
        Material strokeMaterial = GetQuestStrokeMaterial();
        if (strokeMaterial != null)
        {
            activeQuestStrokeLine.material = strokeMaterial;
        }

        UpdateQuestStrokePreview();
    }

    private void UpdateQuestStrokePreview()
    {
        if (!showQuestStrokePreview || activeQuestStrokeLine == null)
        {
            return;
        }

        activeQuestStrokeLine.startWidth = strokeLineWidth;
        activeQuestStrokeLine.endWidth = strokeLineWidth;
        activeQuestStrokeLine.startColor = strokeColor;
        activeQuestStrokeLine.endColor = strokeColor;

        if (currentQuestStrokePoints.Count == 1)
        {
            Vector3 firstPoint = GetQuestStrokePreviewPoint(currentQuestStrokePoints[0]);
            activeQuestStrokeLine.positionCount = 2;
            activeQuestStrokeLine.SetPosition(0, firstPoint);
            activeQuestStrokeLine.SetPosition(1, firstPoint + GetPreviewFallbackDirection() * previewMinimumVisibleLength);
            return;
        }

        activeQuestStrokeLine.positionCount = currentQuestStrokePoints.Count;
        for (int i = 0; i < currentQuestStrokePoints.Count; i++)
        {
            activeQuestStrokeLine.SetPosition(i, GetQuestStrokePreviewPoint(currentQuestStrokePoints[i]));
        }
    }

    private Vector3 GetQuestStrokePreviewPoint(Vector3 worldPoint)
    {
        if (!keepQuestStrokePreviewVisible)
        {
            return worldPoint;
        }

        Transform cameraTransform = depthProjectionCamera != null ? depthProjectionCamera : referenceCamera;
        if (cameraTransform == null)
        {
            Camera mainCamera = Camera.main;
            cameraTransform = mainCamera != null ? mainCamera.transform : null;
        }

        if (cameraTransform == null)
        {
            return worldPoint;
        }

        Vector3 cameraToPoint = worldPoint - cameraTransform.position;
        float distance = cameraToPoint.magnitude;
        if (distance <= 0.001f)
        {
            return worldPoint;
        }

        float previewDistance = Mathf.Max(0.05f, distance - questStrokePreviewCameraOffset);
        return cameraTransform.position + cameraToPoint / distance * previewDistance;
    }

    private Vector3 GetPreviewFallbackDirection()
    {
        if (referenceCamera != null)
        {
            return referenceCamera.right.normalized;
        }

        Camera mainCamera = Camera.main;
        if (mainCamera != null)
        {
            return mainCamera.transform.right.normalized;
        }

        return Vector3.right;
    }

    private Material GetQuestStrokeMaterial()
    {
        if (questStrokeMaterial != null)
        {
            questStrokeMaterial.color = strokeColor;
            ConfigureQuestStrokeMaterial(questStrokeMaterial);
            return questStrokeMaterial;
        }

        Shader shader = Shader.Find("Hidden/Internal-Colored");
        if (shader == null)
        {
            shader = Shader.Find("Sprites/Default");
        }

        if (shader == null)
        {
            shader = Shader.Find("Unlit/Color");
        }

        if (shader == null)
        {
            shader = Shader.Find("Universal Render Pipeline/Unlit");
        }

        if (shader == null)
        {
            shader = Shader.Find("Standard");
        }

        if (shader == null)
        {
            return null;
        }

        questStrokeMaterial = new Material(shader);
        questStrokeMaterial.color = strokeColor;
        ConfigureQuestStrokeMaterial(questStrokeMaterial);
        return questStrokeMaterial;
    }

    private void ConfigureQuestStrokeMaterial(Material material)
    {
        if (material == null)
        {
            return;
        }

        material.SetInt("_SrcBlend", (int)UnityEngine.Rendering.BlendMode.SrcAlpha);
        material.SetInt("_DstBlend", (int)UnityEngine.Rendering.BlendMode.OneMinusSrcAlpha);
        material.SetInt("_Cull", (int)UnityEngine.Rendering.CullMode.Off);
        material.SetInt("_ZWrite", 0);
        material.SetInt("_ZTest", (int)UnityEngine.Rendering.CompareFunction.Always);
        material.renderQueue = 5000;
    }

    private void FinishActiveStrokePreview()
    {
        if (activeQuestStrokeLine == null)
        {
            return;
        }

        GameObject strokeObject = activeQuestStrokeLine.gameObject;
        activeQuestStrokeLine = null;

        if (strokeObject != null)
        {
            Destroy(strokeObject, questStrokeLifetimeSeconds);
        }
    }

    private AudioFrame TryBuildAudioFrame()
    {
        if (!sendQuestMicrophoneAudio)
        {
            return null;
        }

        EnsureMicrophoneCapture();
        if (microphoneClip == null)
        {
            return null;
        }

        int packetRate = Mathf.Clamp(audioPacketRateHz, 1, 60);
        if (Time.unscaledTime < nextAudioPacketTime)
        {
            return null;
        }

        int microphonePosition = Microphone.GetPosition(activeMicrophoneDeviceName);
        if (microphonePosition < 0 || microphoneClip.samples <= 0)
        {
            return null;
        }

        int sourceChannels = Mathf.Max(1, microphoneClip.channels);
        int clipFrameCount = microphoneClip.samples;
        int captureSampleRate = Mathf.Max(1, microphoneClip.frequency);
        int outputSampleRate = GetNetworkAudioSampleRate(captureSampleRate);
        int outputChannels = GetNetworkAudioChannelCount(sourceChannels);
        int targetPacketFrameCount = Mathf.Max(1, Mathf.RoundToInt((float)captureSampleRate / packetRate));
        int availableFrameCount = GetAvailableMicrophoneFrames(microphonePosition, clipFrameCount);
        if (availableFrameCount < targetPacketFrameCount)
        {
            LogAudioStatus("waiting for microphone samples, position=" + microphonePosition +
                           ", availableFrames=" + availableFrameCount +
                           ", neededFrames=" + targetPacketFrameCount);
            return null;
        }

        int maxPacketFrameCount = Mathf.Max(
            targetPacketFrameCount,
            Mathf.RoundToInt(captureSampleRate * maximumAudioPacketDurationSeconds));
        int packetFrameCount = Mathf.Min(targetPacketFrameCount, maxPacketFrameCount);

        if (availableFrameCount > maxPacketFrameCount * 4)
        {
            microphoneReadPosition = microphonePosition - maxPacketFrameCount;
            if (microphoneReadPosition < 0)
            {
                microphoneReadPosition += clipFrameCount;
            }

            packetFrameCount = maxPacketFrameCount;
        }

        int outputFrameCount = GetResampledFrameCount(packetFrameCount, captureSampleRate, outputSampleRate);
        int sourceSampleValueCount = packetFrameCount * sourceChannels;
        int outputSampleValueCount = outputFrameCount * outputChannels;
        EnsureAudioBuffers(sourceSampleValueCount, outputSampleValueCount);
        ReadMicrophoneSamples(packetFrameCount, sourceChannels, clipFrameCount);
        MeasureFloatSamples(audioFloatBuffer, sourceSampleValueCount, out float inputRms, out float inputPeak);
        ConvertAudioForNetwork(packetFrameCount, sourceChannels, captureSampleRate, outputFrameCount, outputChannels, outputSampleRate);
        microphoneReadPosition = (microphoneReadPosition + packetFrameCount) % clipFrameCount;
        AdvanceNextAudioPacketTime(packetRate);

        int byteCount = EncodePcm16(outputSampleValueCount);
        AudioFrame audioFrame = new AudioFrame();
        audioFrame.sequence = audioSequence;
        audioSequence++;
        audioFrame.sampleRate = outputSampleRate;
        audioFrame.channels = outputChannels;
        audioFrame.sampleCount = outputFrameCount;
        audioFrame.encoding = "PCM16_LE_BASE64";
        audioFrame.timestamp = Time.unscaledTime;
        audioFrame.samplesBase64 = Convert.ToBase64String(audioByteBuffer, 0, byteCount);
        WriteOutgoingAudioWav(audioFrame.sampleRate, audioFrame.channels, audioByteBuffer, byteCount);
        sentAudioFrameCount++;
        WriteAudioDiagnosticsRow("sent", audioFrame.sequence, audioFrame.sampleRate, audioFrame.channels, audioFrame.sampleCount, byteCount, inputRms, inputPeak);
        LogAudioStatus("sent audio frame count=" + sentAudioFrameCount +
                       ", sequence=" + audioFrame.sequence +
                       ", sampleRate=" + audioFrame.sampleRate +
                       ", captureSampleRate=" + captureSampleRate +
                       ", channels=" + audioFrame.channels +
                       ", sampleCount=" + audioFrame.sampleCount +
                       ", bytes=" + byteCount +
                       ", inputRms=" + inputRms.ToString("F4") +
                       ", inputPeak=" + inputPeak.ToString("F4"));
        return audioFrame;
    }

    private int GetAvailableMicrophoneFrames(int microphonePosition, int clipFrameCount)
    {
        if (microphonePosition >= microphoneReadPosition)
        {
            return microphonePosition - microphoneReadPosition;
        }

        return clipFrameCount - microphoneReadPosition + microphonePosition;
    }

    private void EnsureAudioBuffers(int sourceSampleValueCount, int outputSampleValueCount)
    {
        if (audioFloatBuffer == null || audioFloatBuffer.Length != sourceSampleValueCount)
        {
            audioFloatBuffer = new float[sourceSampleValueCount];
        }

        if (audioOutputFloatBuffer == null || audioOutputFloatBuffer.Length != outputSampleValueCount)
        {
            audioOutputFloatBuffer = new float[outputSampleValueCount];
        }

        int byteCount = outputSampleValueCount * 2;
        if (audioByteBuffer == null || audioByteBuffer.Length != byteCount)
        {
            audioByteBuffer = new byte[byteCount];
        }
    }

    private void ReadMicrophoneSamples(int frameCount, int channels, int clipFrameCount)
    {
        if (microphoneReadPosition + frameCount <= clipFrameCount)
        {
            microphoneClip.GetData(audioFloatBuffer, microphoneReadPosition);
            return;
        }

        int firstFrameCount = clipFrameCount - microphoneReadPosition;
        int firstValueCount = firstFrameCount * channels;
        float[] firstBuffer = new float[firstValueCount];
        microphoneClip.GetData(firstBuffer, microphoneReadPosition);
        Array.Copy(firstBuffer, 0, audioFloatBuffer, 0, firstValueCount);

        int secondValueCount = audioFloatBuffer.Length - firstValueCount;
        if (secondValueCount <= 0)
        {
            return;
        }

        float[] secondBuffer = new float[secondValueCount];
        microphoneClip.GetData(secondBuffer, 0);
        Array.Copy(secondBuffer, 0, audioFloatBuffer, firstValueCount, secondValueCount);
    }

    private int GetNetworkAudioSampleRate(int captureSampleRate)
    {
        if (!resampleAudioToConfiguredSampleRate)
        {
            return Mathf.Clamp(captureSampleRate, 8000, 48000);
        }

        return Mathf.Clamp(audioSampleRate, 8000, 48000);
    }

    private int GetNetworkAudioChannelCount(int sourceChannels)
    {
        if (downmixAudioToMono)
        {
            return 1;
        }

        return Mathf.Clamp(sourceChannels, 1, 2);
    }

    private static int GetResampledFrameCount(int sourceFrameCount, int sourceSampleRate, int outputSampleRate)
    {
        if (sourceFrameCount <= 0 || sourceSampleRate <= 0 || outputSampleRate <= 0)
        {
            return 0;
        }

        return Mathf.Max(1, Mathf.RoundToInt(sourceFrameCount * ((float)outputSampleRate / sourceSampleRate)));
    }

    private void ConvertAudioForNetwork(
        int sourceFrameCount,
        int sourceChannels,
        int sourceSampleRate,
        int outputFrameCount,
        int outputChannels,
        int outputSampleRate)
    {
        if (audioFloatBuffer == null || audioOutputFloatBuffer == null || sourceFrameCount <= 0 || outputFrameCount <= 0)
        {
            return;
        }

        sourceChannels = Mathf.Max(1, sourceChannels);
        outputChannels = Mathf.Max(1, outputChannels);

        float sourceFramesPerOutputFrame = outputSampleRate > 0
            ? (float)sourceSampleRate / outputSampleRate
            : 1f;

        for (int outputFrame = 0; outputFrame < outputFrameCount; outputFrame++)
        {
            float sourceFrameFloat = outputFrame * sourceFramesPerOutputFrame;
            int sourceFrame0 = Mathf.Clamp(Mathf.FloorToInt(sourceFrameFloat), 0, sourceFrameCount - 1);
            int sourceFrame1 = Mathf.Min(sourceFrame0 + 1, sourceFrameCount - 1);
            float blend = Mathf.Clamp01(sourceFrameFloat - sourceFrame0);

            for (int outputChannel = 0; outputChannel < outputChannels; outputChannel++)
            {
                float sample = outputChannels == 1
                    ? ReadMixedSourceFrame(sourceFrame0, sourceFrame1, blend, sourceChannels)
                    : ReadInterpolatedSourceSample(sourceFrame0, sourceFrame1, blend, Mathf.Min(outputChannel, sourceChannels - 1), sourceChannels);

                audioOutputFloatBuffer[outputFrame * outputChannels + outputChannel] = sample;
            }
        }
    }

    private float ReadMixedSourceFrame(int sourceFrame0, int sourceFrame1, float blend, int sourceChannels)
    {
        float sum = 0f;
        for (int channel = 0; channel < sourceChannels; channel++)
        {
            sum += ReadInterpolatedSourceSample(sourceFrame0, sourceFrame1, blend, channel, sourceChannels);
        }

        return sum / sourceChannels;
    }

    private float ReadInterpolatedSourceSample(int sourceFrame0, int sourceFrame1, float blend, int channel, int sourceChannels)
    {
        int index0 = sourceFrame0 * sourceChannels + channel;
        int index1 = sourceFrame1 * sourceChannels + channel;
        float sample0 = index0 >= 0 && index0 < audioFloatBuffer.Length ? audioFloatBuffer[index0] : 0f;
        float sample1 = index1 >= 0 && index1 < audioFloatBuffer.Length ? audioFloatBuffer[index1] : sample0;
        return Mathf.Lerp(sample0, sample1, blend);
    }

    private void AdvanceNextAudioPacketTime(int packetRate)
    {
        float interval = 1f / Mathf.Max(1, packetRate);
        if (nextAudioPacketTime <= 0f || Time.unscaledTime - nextAudioPacketTime > interval * Mathf.Max(1, maximumAudioPacketsPerUpdate))
        {
            nextAudioPacketTime = Time.unscaledTime + interval;
            return;
        }

        nextAudioPacketTime += interval;
    }

    private int EncodePcm16(int sampleValueCount)
    {
        float gain = Mathf.Max(0f, audioGain);
        float ceiling = Mathf.Clamp(audioLimiterCeiling, 0.1f, 1f);
        for (int i = 0; i < sampleValueCount; i++)
        {
            float sample = ApplySoftLimiter(audioOutputFloatBuffer[i] * gain, ceiling);
            short pcm = sample < 0f
                ? (short)Mathf.RoundToInt(sample * 32768f)
                : (short)Mathf.RoundToInt(sample * 32767f);
            int byteIndex = i * 2;
            audioByteBuffer[byteIndex] = (byte)(pcm & 0xff);
            audioByteBuffer[byteIndex + 1] = (byte)((pcm >> 8) & 0xff);
        }

        return sampleValueCount * 2;
    }

    private void EnsureMicrophoneCapture()
    {
        if (!sendQuestMicrophoneAudio || microphoneStartRequested || microphonePermissionDenied || microphoneStartFailed)
        {
            return;
        }

        if (Time.unscaledTime < earliestMicrophoneStartTime)
        {
            return;
        }

        if (microphoneClip != null && Microphone.IsRecording(activeMicrophoneDeviceName))
        {
            return;
        }

        StartCoroutine(StartMicrophoneWhenAuthorized());
    }

    private IEnumerator StartMicrophoneWhenAuthorized()
    {
        microphoneStartRequested = true;

        if (!Application.HasUserAuthorization(UserAuthorization.Microphone))
        {
            yield return Application.RequestUserAuthorization(UserAuthorization.Microphone);
        }

        if (!isSending || !sendQuestMicrophoneAudio)
        {
            microphoneStartRequested = false;
            yield break;
        }

        if (!Application.HasUserAuthorization(UserAuthorization.Microphone))
        {
            Debug.LogWarning("QuestHandDataSender cannot send microphone audio because microphone permission was not granted.");
            microphonePermissionDenied = true;
            microphoneStartRequested = false;
            yield break;
        }

        string deviceName = TrimToNull(microphoneDeviceName);
        string[] devices = Microphone.devices;
        if (logAudioStatus)
        {
            Debug.Log("QuestHandDataSender microphone devices: " + (devices == null || devices.Length == 0 ? "(none)" : string.Join(", ", devices)));
        }

        if (!string.IsNullOrEmpty(deviceName) && !IsMicrophoneDeviceAvailable(deviceName))
        {
            Debug.LogWarning("QuestHandDataSender microphone device '" + deviceName + "' was not found. Falling back to the default microphone.");
            deviceName = null;
        }

        int requestedSampleRate = Mathf.Clamp(audioSampleRate, 8000, 48000);
        try
        {
            microphoneClip = Microphone.Start(deviceName, true, 10, requestedSampleRate);
            activeMicrophoneDeviceName = deviceName;
            microphoneReadPosition = 0;
            audioSequence = 0;
            nextAudioPacketTime = 0f;

            if (microphoneClip == null)
            {
                microphoneStartFailed = true;
                Debug.LogWarning("QuestHandDataSender could not start microphone capture because Microphone.Start returned no clip.");
            }
            else if (logAudioStatus)
            {
                Debug.Log("QuestHandDataSender microphone capture started, device=" + (activeMicrophoneDeviceName ?? "(default)") +
                          ", frequency=" + microphoneClip.frequency +
                          ", channels=" + microphoneClip.channels +
                          ", samples=" + microphoneClip.samples);
            }

            if (microphoneClip != null)
            {
                WriteAudioDiagnosticsEvent("microphone_started", microphoneClip.frequency, microphoneClip.channels, microphoneClip.samples);
            }
        }
        catch (Exception e)
        {
            microphoneClip = null;
            activeMicrophoneDeviceName = null;
            microphoneStartFailed = true;
            Debug.LogWarning("QuestHandDataSender could not start microphone capture: " + e.Message);
        }

        microphoneStartRequested = false;
    }

    private void StopMicrophoneCapture()
    {
        if (microphoneClip != null || microphoneStartRequested)
        {
            try
            {
                if (Microphone.IsRecording(activeMicrophoneDeviceName))
                {
                    Microphone.End(activeMicrophoneDeviceName);
                }
            }
            catch (Exception e)
            {
                Debug.LogWarning("QuestHandDataSender could not stop microphone capture cleanly: " + e.Message);
            }
        }

        microphoneClip = null;
        activeMicrophoneDeviceName = null;
        microphoneReadPosition = 0;
        microphoneStartRequested = false;
        earliestMicrophoneStartTime = 0f;
    }

    private static bool IsMicrophoneDeviceAvailable(string deviceName)
    {
        if (string.IsNullOrEmpty(deviceName))
        {
            return true;
        }

        string[] devices = Microphone.devices;
        if (devices == null)
        {
            return false;
        }

        for (int i = 0; i < devices.Length; i++)
        {
            if (devices[i] == deviceName)
            {
                return true;
            }
        }

        return false;
    }

    private void LogAudioStatus(string message)
    {
        if (!logAudioStatus || Time.unscaledTime < nextAudioStatusLogTime)
        {
            return;
        }

        nextAudioStatusLogTime = Time.unscaledTime + 2f;
        Debug.Log("QuestHandDataSender audio: " + message);
    }

    private void WriteAudioDiagnosticsRow(string eventName, int sequence, int sampleRate, int channels, int sampleCount, int byteCount, float inputRms, float inputPeak)
    {
        StreamWriter writer = GetAudioDiagnosticsWriter();
        if (writer == null)
        {
            return;
        }

        writer.WriteLine(string.Join(",",
            FormatFloat(Time.unscaledTime),
            eventName,
            sequence.ToString(CultureInfo.InvariantCulture),
            sampleRate.ToString(CultureInfo.InvariantCulture),
            channels.ToString(CultureInfo.InvariantCulture),
            sampleCount.ToString(CultureInfo.InvariantCulture),
            byteCount.ToString(CultureInfo.InvariantCulture),
            FormatFloat(inputRms),
            FormatFloat(inputPeak),
            EscapeCsv(targetEndPoint != null ? targetEndPoint.ToString() : "")));

        FlushAudioDiagnosticsIfNeeded(writer);
    }

    private void WriteAudioDiagnosticsEvent(string eventName, int sampleRate, int channels, int sampleCount)
    {
        StreamWriter writer = GetAudioDiagnosticsWriter();
        if (writer == null)
        {
            return;
        }

        writer.WriteLine(string.Join(",",
            FormatFloat(Time.unscaledTime),
            eventName,
            "",
            sampleRate.ToString(CultureInfo.InvariantCulture),
            channels.ToString(CultureInfo.InvariantCulture),
            sampleCount.ToString(CultureInfo.InvariantCulture),
            "",
            "",
            "",
            EscapeCsv(activeMicrophoneDeviceName ?? "(default)")));

        FlushAudioDiagnosticsIfNeeded(writer);
    }

    private StreamWriter GetAudioDiagnosticsWriter()
    {
        if (!saveAudioDiagnosticsToFile)
        {
            return null;
        }

        if (audioDiagnosticsWriter != null)
        {
            return audioDiagnosticsWriter;
        }

        try
        {
            string directory = GetAudioDiagnosticsDirectory();
            Directory.CreateDirectory(directory);
            string filePath = Path.Combine(directory, "quest_sender_audio.csv");
            bool writeHeader = !File.Exists(filePath) || new FileInfo(filePath).Length == 0;
            audioDiagnosticsWriter = new StreamWriter(filePath, true);
            if (writeHeader)
            {
                audioDiagnosticsWriter.WriteLine("time,event,sequence,sampleRate,channels,sampleCount,byteCount,inputRms,inputPeak,target");
            }

            Debug.Log("QuestHandDataSender audio diagnostics file: " + filePath);
            return audioDiagnosticsWriter;
        }
        catch (Exception e)
        {
            Debug.LogWarning("QuestHandDataSender could not open audio diagnostics file: " + e.Message);
            saveAudioDiagnosticsToFile = false;
            return null;
        }
    }

    private string GetAudioDiagnosticsDirectory()
    {
#if UNITY_EDITOR
        string root = Path.GetFullPath(Path.Combine(Application.dataPath, ".."));
#else
        string root = Application.persistentDataPath;
#endif
        string folderName = string.IsNullOrEmpty(audioDiagnosticsFolderName) ? "AudioDiagnostics" : audioDiagnosticsFolderName;
        return Path.Combine(root, folderName);
    }

    private void FlushAudioDiagnosticsIfNeeded(StreamWriter writer)
    {
        if (Time.unscaledTime < nextAudioDiagnosticsFlushTime)
        {
            return;
        }

        nextAudioDiagnosticsFlushTime = Time.unscaledTime + 1f;
        writer.Flush();
    }

    private void CloseAudioDiagnosticsWriter()
    {
        if (audioDiagnosticsWriter == null)
        {
            return;
        }

        audioDiagnosticsWriter.Flush();
        audioDiagnosticsWriter.Dispose();
        audioDiagnosticsWriter = null;
    }

    private void WriteOutgoingAudioWav(int sampleRate, int channels, byte[] pcmBytes, int byteCount)
    {
        if (!saveOutgoingAudioWav || pcmBytes == null || byteCount <= 0)
        {
            return;
        }

        try
        {
            sampleRate = Mathf.Clamp(sampleRate, 8000, 48000);
            channels = Mathf.Clamp(channels, 1, 2);
            if (outgoingAudioWavWriter == null ||
                outgoingAudioWavSampleRate != sampleRate ||
                outgoingAudioWavChannels != channels)
            {
                CloseOutgoingAudioWavWriter();
                string directory = GetAudioWavDirectory(outgoingAudioWavSubfolderName);
                string filePath = BuildAudioWavPath(directory, outgoingAudioWavFileName, timestampAudioWavFiles);
                outgoingAudioWavWriter = new Pcm16WavWriter(filePath, sampleRate, channels);
                outgoingAudioWavSampleRate = sampleRate;
                outgoingAudioWavChannels = channels;
                Debug.Log("QuestHandDataSender outgoing audio WAV file: " + filePath);
            }

            outgoingAudioWavWriter.WritePcm16(pcmBytes, 0, byteCount);
        }
        catch (Exception e)
        {
            Debug.LogWarning("QuestHandDataSender could not write outgoing audio WAV: " + e.Message);
            CloseOutgoingAudioWavWriter();
            saveOutgoingAudioWav = false;
        }
    }

    private void CloseOutgoingAudioWavWriter()
    {
        if (outgoingAudioWavWriter == null)
        {
            return;
        }

        outgoingAudioWavWriter.Dispose();
        outgoingAudioWavWriter = null;
        outgoingAudioWavSampleRate = 0;
        outgoingAudioWavChannels = 0;
    }

    private string GetAudioWavDirectory(string subfolderName)
    {
#if UNITY_EDITOR
        string root = Path.GetFullPath(Path.Combine(Application.dataPath, ".."));
#else
        string root = Application.persistentDataPath;
#endif
        string folderName = string.IsNullOrEmpty(audioWavFolderName) ? "AudioWavCaptures" : audioWavFolderName;
        string directory = Path.Combine(root, folderName);
        if (!string.IsNullOrEmpty(subfolderName))
        {
            directory = Path.Combine(directory, subfolderName);
        }

        return directory;
    }

    private static string BuildAudioWavPath(string directory, string fileName, bool includeTimestamp)
    {
        Directory.CreateDirectory(directory);
        string safeFileName = string.IsNullOrEmpty(fileName) ? "audio.wav" : fileName;
        string extension = Path.GetExtension(safeFileName);
        if (string.IsNullOrEmpty(extension))
        {
            extension = ".wav";
        }

        string name = Path.GetFileNameWithoutExtension(safeFileName);
        if (string.IsNullOrEmpty(name))
        {
            name = "audio";
        }

        if (includeTimestamp)
        {
            name += "_" + DateTime.Now.ToString("yyyyMMdd_HHmmss", CultureInfo.InvariantCulture);
        }

        return Path.Combine(directory, name + extension);
    }

    private static float ApplySoftLimiter(float value, float ceiling)
    {
        ceiling = Mathf.Clamp(ceiling, 0.1f, 1f);
        float abs = Mathf.Abs(value);
        if (abs <= ceiling)
        {
            return value;
        }

        float sign = value < 0f ? -1f : 1f;
        float excess = abs - ceiling;
        float limited = ceiling + (1f - ceiling) * (excess / (excess + 1f));
        return sign * Mathf.Min(limited, 1f);
    }

    private static string FormatFloat(float value)
    {
        return value.ToString("F6", CultureInfo.InvariantCulture);
    }

    private static string EscapeCsv(string value)
    {
        if (string.IsNullOrEmpty(value))
        {
            return "";
        }

        return "\"" + value.Replace("\"", "\"\"") + "\"";
    }

    private static void MeasureFloatSamples(float[] samples, int count, out float rms, out float peak)
    {
        rms = 0f;
        peak = 0f;
        if (samples == null || count <= 0)
        {
            return;
        }

        double sumSquares = 0.0;
        int safeCount = Mathf.Min(count, samples.Length);
        for (int i = 0; i < safeCount; i++)
        {
            float abs = Mathf.Abs(samples[i]);
            if (abs > peak)
            {
                peak = abs;
            }

            sumSquares += samples[i] * samples[i];
        }

        rms = Mathf.Sqrt((float)(sumSquares / safeCount));
    }

    private bool IsHandTracked(OVRHand hand, OVRSkeleton skeleton)
    {
        if (skeleton == null || !skeleton.IsInitialized || !skeleton.IsDataValid || skeleton.Bones == null || skeleton.Bones.Count == 0)
        {
            return false;
        }

        if (requireHighConfidence && !skeleton.IsDataHighConfidence)
        {
            return false;
        }

        if (hand == null)
        {
            return true;
        }

        if (!hand.IsTracked || !hand.IsDataValid)
        {
            return false;
        }

        return !requireHighConfidence || hand.IsDataHighConfidence;
    }

    private bool ResolveTargetEndPoint()
    {
        if (Time.unscaledTime < nextTargetResolveTime)
        {
            return targetEndPoint != null;
        }

        nextTargetResolveTime = Time.unscaledTime + Mathf.Max(0.1f, targetResolveRetrySeconds);

        string host = GetTargetHost();
        if (string.IsNullOrEmpty(host))
        {
            if (!warnedAboutMissingHost)
            {
                warnedAboutMissingHost = true;
                Debug.LogWarning("QuestHandDataSender has no target IP. Set targetHost or fill run_once.host.");
            }

            return false;
        }

        if (targetEndPoint != null && host == resolvedHost && targetPort == resolvedPort)
        {
            return true;
        }

        try
        {
            IPAddress address;
            if (!IPAddress.TryParse(host, out address))
            {
                if (!allowDnsHostResolution)
                {
                    if (!warnedAboutMissingHost)
                    {
                        warnedAboutMissingHost = true;
                        Debug.LogWarning("QuestHandDataSender targetHost is not an IP address. Use a direct IPv4 address or enable allowDnsHostResolution.");
                    }

                    return false;
                }

                IPAddress[] addresses = Dns.GetHostAddresses(host);
                address = PickAddress(addresses);
            }

            if (address == null)
            {
                Debug.LogWarning("QuestHandDataSender could not resolve target host: " + host);
                return false;
            }

            targetEndPoint = new IPEndPoint(address, targetPort);
            resolvedHost = host;
            resolvedPort = targetPort;
            warnedAboutMissingHost = false;
            WarnIfLinkLocalAddress(address);

            if (logConnectionChanges)
            {
                Debug.Log("QuestHandDataSender target is " + targetEndPoint);
            }

            return true;
        }
        catch (Exception e)
        {
            targetEndPoint = null;
            Debug.LogWarning("QuestHandDataSender could not resolve target host '" + host + "': " + e.Message);
            return false;
        }
    }

    private string GetTargetHost()
    {
        string explicitTargetHost = TrimToNull(targetHost);
        if (!string.IsNullOrEmpty(explicitTargetHost))
        {
            return explicitTargetHost;
        }

        if (useLocalhostInEditor && Application.isEditor)
        {
            string editorHost = TrimToNull(editorTargetHost);
            if (!string.IsNullOrEmpty(editorHost))
            {
                return editorHost;
            }
        }

        if (useRunOnceHost)
        {
            string runOnceStaticHost = TrimToNull(run_once.host_address);
            if (!string.IsNullOrEmpty(runOnceStaticHost))
            {
                return runOnceStaticHost;
            }

            run_once runOnce = FindObjectOfType<run_once>();
            string runOnceSceneHost = runOnce != null ? TrimToNull(runOnce.host) : null;
            if (!string.IsNullOrEmpty(runOnceSceneHost))
            {
                return runOnceSceneHost;
            }
        }

        return null;
    }

    private static string TrimToNull(string value)
    {
        if (string.IsNullOrEmpty(value))
        {
            return null;
        }

        string trimmed = value.Trim();
        return string.IsNullOrEmpty(trimmed) ? null : trimmed;
    }

    private static IPAddress PickAddress(IPAddress[] addresses)
    {
        if (addresses == null || addresses.Length == 0)
        {
            return null;
        }

        for (int i = 0; i < addresses.Length; i++)
        {
            if (addresses[i] != null && addresses[i].AddressFamily == AddressFamily.InterNetwork)
            {
                return addresses[i];
            }
        }

        return addresses[0];
    }

    private void WarnIfLinkLocalAddress(IPAddress address)
    {
        if (!warnAboutLinkLocalTarget || warnedAboutLinkLocalTarget || address == null)
        {
            return;
        }

        byte[] bytes = address.GetAddressBytes();
        bool isIpv4LinkLocal = address.AddressFamily == AddressFamily.InterNetwork &&
                               bytes.Length == 4 &&
                               bytes[0] == 169 &&
                               bytes[1] == 254;

        if (!isIpv4LinkLocal)
        {
            return;
        }

        warnedAboutLinkLocalTarget = true;
        Debug.LogWarning("QuestHandDataSender target uses a 169.254.x.x link-local IP. " +
                         "That often only works for USB/direct connections. For Quest-to-HoloLens over Wi-Fi, use the HoloLens Wi-Fi IPv4 address.");
    }

    private void FindHandSources()
    {
        if (leftSkeleton == null)
        {
            leftSkeleton = FindSkeleton(true);
        }

        if (rightSkeleton == null)
        {
            rightSkeleton = FindSkeleton(false);
        }

        if (leftHand == null)
        {
            leftHand = FindHandForSkeleton(leftSkeleton, true);
        }

        if (rightHand == null)
        {
            rightHand = FindHandForSkeleton(rightSkeleton, false);
        }
    }

    private void FindReferenceCamera()
    {
        Camera mainCamera = Camera.main;
        if (mainCamera != null)
        {
            referenceCamera = mainCamera.transform;
            return;
        }

        if (!string.IsNullOrEmpty(referenceCameraName))
        {
            GameObject namedCamera = GameObject.Find(referenceCameraName);
            if (namedCamera != null)
            {
                referenceCamera = namedCamera.transform;
                return;
            }
        }

        Camera camera = FindObjectOfType<Camera>();
        if (camera != null)
        {
            referenceCamera = camera.transform;
        }
    }

    private void FindDepthProjectionSource()
    {
        depthProjectionSource = FindObjectOfType<DepthDistance>();
        if (depthProjectionSource != null)
        {
            warnedAboutMissingDepthProjectionSource = false;
        }
    }

    private void FindBillboardMarkerSource()
    {
        if (depthProjectionSource == null && autoFindDepthProjectionSource)
        {
            FindDepthProjectionSource();
        }

        billboardMarkerSource = depthProjectionSource != null
            ? depthProjectionSource.fingerPositionRef
            : FindObjectOfType<FingerPosition>();
    }

    private OVRSkeleton FindSkeleton(bool left)
    {
        string anchorName = left ? leftHandAnchorName : rightHandAnchorName;
        GameObject anchor = string.IsNullOrEmpty(anchorName) ? null : GameObject.Find(anchorName);
        if (anchor != null)
        {
            OVRSkeleton skeleton = anchor.GetComponentInChildren<OVRSkeleton>(true);
            if (skeleton != null)
            {
                return skeleton;
            }
        }

        OVRSkeleton[] skeletons = Resources.FindObjectsOfTypeAll<OVRSkeleton>();
        for (int i = 0; i < skeletons.Length; i++)
        {
            OVRSkeleton skeleton = skeletons[i];
            if (skeleton == null || !IsLoadedSceneObject(skeleton.gameObject))
            {
                continue;
            }

            OVRSkeleton.SkeletonType skeletonType = skeleton.GetSkeletonType();
            if (left && (skeletonType == OVRSkeleton.SkeletonType.HandLeft || skeletonType == OVRSkeleton.SkeletonType.XRHandLeft))
            {
                return skeleton;
            }

            if (!left && (skeletonType == OVRSkeleton.SkeletonType.HandRight || skeletonType == OVRSkeleton.SkeletonType.XRHandRight))
            {
                return skeleton;
            }
        }

        return null;
    }

    private OVRHand FindHandForSkeleton(OVRSkeleton skeleton, bool left)
    {
        if (skeleton != null)
        {
            OVRHand hand = skeleton.GetComponent<OVRHand>();
            if (hand != null)
            {
                return hand;
            }

            hand = skeleton.GetComponentInParent<OVRHand>();
            if (hand != null)
            {
                return hand;
            }

            hand = skeleton.GetComponentInChildren<OVRHand>(true);
            if (hand != null)
            {
                return hand;
            }
        }

        string anchorName = left ? leftHandAnchorName : rightHandAnchorName;
        GameObject anchor = string.IsNullOrEmpty(anchorName) ? null : GameObject.Find(anchorName);
        if (anchor != null)
        {
            return anchor.GetComponentInChildren<OVRHand>(true);
        }

        return null;
    }

    private bool HasBothSkeletons()
    {
        return leftSkeleton != null && rightSkeleton != null;
    }

    private static bool IsLoadedSceneObject(GameObject gameObject)
    {
        return gameObject != null && gameObject.scene.IsValid();
    }

    private static bool IsFinite(float value)
    {
        return !float.IsNaN(value) && !float.IsInfinity(value);
    }

    private static bool IsFinite(Vector3 value)
    {
        return IsFinite(value.x) && IsFinite(value.y) && IsFinite(value.z);
    }

    private static bool IsWristBone(OVRSkeleton.BoneId boneId)
    {
        return boneId == OVRSkeleton.BoneId.Hand_WristRoot ||
               boneId == OVRSkeleton.BoneId.XRHand_Wrist ||
               boneId == OVRSkeleton.BoneId.XRHand_Palm;
    }

    private void OnValidate()
    {
        targetPort = Mathf.Clamp(targetPort, 1, 65535);
        sendRateHz = Mathf.Max(0f, sendRateHz);
        networkStartDelaySeconds = Mathf.Max(0f, networkStartDelaySeconds);
        targetResolveRetrySeconds = Mathf.Max(0.1f, targetResolveRetrySeconds);
        positionScale = Mathf.Max(0.01f, positionScale);
        minimumStrokeDistanceFromCamera = Mathf.Max(0.01f, minimumStrokeDistanceFromCamera);
        maximumStrokeHeadwardJump = Mathf.Max(0f, maximumStrokeHeadwardJump);
        maximumStrokePointJump = Mathf.Max(0f, maximumStrokePointJump);
        strokePointSpacing = Mathf.Max(0.001f, strokePointSpacing);
        questStrokeLifetimeSeconds = Mathf.Max(0f, questStrokeLifetimeSeconds);
        strokeLineWidth = Mathf.Max(0.0001f, strokeLineWidth);
        previewMinimumVisibleLength = Mathf.Max(0.0001f, previewMinimumVisibleLength);
        questStrokePreviewCameraOffset = Mathf.Max(0f, questStrokePreviewCameraOffset);
        webRtcLocalSignalingPort = Mathf.Clamp(webRtcLocalSignalingPort, 1, 65535);
        webRtcRemoteSignalingPort = Mathf.Clamp(webRtcRemoteSignalingPort, 1, 65535);
        webRtcStartupDelaySeconds = Mathf.Max(0f, webRtcStartupDelaySeconds);
        pinchDepthHandSmoothingTime = Mathf.Max(0.001f, pinchDepthHandSmoothingTime);
        pinchDepthHandMaximumSpeed = Mathf.Max(0.01f, pinchDepthHandMaximumSpeed);
        audioSampleRate = Mathf.Clamp(audioSampleRate, 8000, 48000);
        audioPacketRateHz = Mathf.Clamp(audioPacketRateHz, 1, 90);
        audioGain = Mathf.Max(0f, audioGain);
        maximumAudioPacketDurationSeconds = Mathf.Clamp(maximumAudioPacketDurationSeconds, 0.01f, 0.12f);
        maximumAudioPacketsPerUpdate = Mathf.Clamp(maximumAudioPacketsPerUpdate, 1, 8);
        microphoneStartDelaySeconds = Mathf.Max(0f, microphoneStartDelaySeconds);
        audioLimiterCeiling = Mathf.Clamp(audioLimiterCeiling, 0.1f, 1f);
    }

    private sealed class Pcm16WavWriter : IDisposable
    {
        private readonly FileStream stream;
        private readonly BinaryWriter writer;
        private long dataByteCount;
        private bool disposed;

        public Pcm16WavWriter(string filePath, int sampleRate, int channels)
        {
            Directory.CreateDirectory(Path.GetDirectoryName(filePath));
            stream = new FileStream(filePath, FileMode.Create, FileAccess.Write, FileShare.Read);
            writer = new BinaryWriter(stream);
            WriteHeader(sampleRate, channels);
        }

        public void WritePcm16(byte[] pcmBytes, int offset, int count)
        {
            if (disposed || pcmBytes == null || count <= 0)
            {
                return;
            }

            int safeOffset = Mathf.Clamp(offset, 0, pcmBytes.Length);
            int safeCount = Mathf.Clamp(count, 0, pcmBytes.Length - safeOffset);
            if (safeCount <= 0)
            {
                return;
            }

            writer.Write(pcmBytes, safeOffset, safeCount);
            dataByteCount += safeCount;
        }

        public void Dispose()
        {
            if (disposed)
            {
                return;
            }

            disposed = true;
            writer.Flush();
            stream.Seek(4, SeekOrigin.Begin);
            writer.Write(ToUInt32Saturated(36 + dataByteCount));
            stream.Seek(40, SeekOrigin.Begin);
            writer.Write(ToUInt32Saturated(dataByteCount));
            writer.Dispose();
            stream.Dispose();
        }

        private void WriteHeader(int sampleRate, int channels)
        {
            writer.Write(Encoding.ASCII.GetBytes("RIFF"));
            writer.Write((uint)36);
            writer.Write(Encoding.ASCII.GetBytes("WAVE"));
            writer.Write(Encoding.ASCII.GetBytes("fmt "));
            writer.Write((uint)16);
            writer.Write((ushort)1);
            writer.Write((ushort)channels);
            writer.Write((uint)sampleRate);
            writer.Write((uint)(sampleRate * channels * 2));
            writer.Write((ushort)(channels * 2));
            writer.Write((ushort)16);
            writer.Write(Encoding.ASCII.GetBytes("data"));
            writer.Write((uint)0);
        }

        private static uint ToUInt32Saturated(long value)
        {
            if (value <= 0)
            {
                return 0;
            }

            return value > uint.MaxValue ? uint.MaxValue : (uint)value;
        }
    }

    private sealed class TransformPair
    {
        public Transform source;
        public Transform preview;
    }

    private sealed class RendererState
    {
        public Renderer renderer;
        public bool enabled;
    }

    [Serializable]
    private sealed class HandFramePacket
    {
        public string packetType;
        public string poseSpace;
        public HandFrame[] hands;
        public StrokeEvent[] strokeEvents;
        public AudioFrame audioFrame;
    }

    [Serializable]
    private sealed class HandFrame
    {
        public string handedness;
        public bool isTracked;
        public PoseData wrist;
        public JointPose[] joints;
    }

    [Serializable]
    private struct JointPose
    {
        public string name;
        public PoseData pose;
    }

    [Serializable]
    private sealed class StrokeEvent
    {
        public string id;
        public string action;
        public PoseData point;
        public float width;
        public Color color;
        public float timestamp;
    }

    [Serializable]
    private sealed class AudioFrame
    {
        public int sequence;
        public int sampleRate;
        public int channels;
        public int sampleCount;
        public string encoding;
        public string samplesBase64;
        public float timestamp;
    }

    [Serializable]
    private struct PoseData
    {
        public bool isValid;
        public Vector3 position;
        public Quaternion rotation;

        public static readonly PoseData Invalid = new PoseData
        {
            isValid = false,
            position = Vector3.zero,
            rotation = Quaternion.identity
        };

        public static PoseData FromTransform(
            Transform source,
            Transform reference,
            float scale,
            Vector3 worldPositionOffset)
        {
            if (source == null)
            {
                return Invalid;
            }

            Vector3 worldPosition = source.position + worldPositionOffset;
            if (reference == null)
            {
                return new PoseData
                {
                    isValid = true,
                    position = worldPosition * scale,
                    rotation = source.rotation
                };
            }

            return new PoseData
            {
                isValid = true,
                position = reference.InverseTransformPoint(worldPosition) * scale,
                rotation = Quaternion.Inverse(reference.rotation) * source.rotation
            };
        }

        public static PoseData FromPosition(
            Vector3 worldPosition,
            Transform reference,
            float scale,
            Vector3 worldPositionOffset)
        {
            Vector3 shiftedWorldPosition = worldPosition + worldPositionOffset;
            if (reference == null)
            {
                return new PoseData
                {
                    isValid = true,
                    position = shiftedWorldPosition * scale,
                    rotation = Quaternion.identity
                };
            }

            return new PoseData
            {
                isValid = true,
                position = reference.InverseTransformPoint(shiftedWorldPosition) * scale,
                rotation = Quaternion.identity
            };
        }
    }
}
